# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
- main
- OIHP-1421-openhim-mediator-hl7-validator

pr:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:

- stage: Prepare
  jobs:
  - job: 
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core 5 sdk'
      inputs:
        version: 5.0.x
        performMultiLevelLookup: true
        includePreviewVersions: true

- stage: Build
  jobs:
  - job: 
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
    
- stage: Test
  jobs:
  - job: 
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test $(buildConfiguration)'
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
    
